// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/// <reference types="node" />
import "dotenv/config";
import { defineConfig } from "prisma/config";

// 1. Check if it exists AT RUNTIME
if (!process.env.DATABASE_URL) {
  // If it's missing, crash the app gracefully with a helpful message!
  throw new Error("CRITICAL ERROR: DATABASE_URL is missing from .env file.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
